### ISSUE TITLE
yutiriti>=1.0.0 mistaken library

### ISSUE THREAD

**Issue by defcore22** [hxAri/ILAPIs#8]
this library doesn't exist "yutiriti>=1.0.0" how or where can ı download this lib?

**Comment by hxAri** [comment]
> this library doesn't exist "yutiriti>=1.0.0" how or where can ı download this lib?

I have included it in the README documentation, at least you have to install it manually [see](https://github.com/hxAri/Yutiriti), or you can download the **Yutiriti** code then put it in the kanashi directory, if you don't want to install it globally

**Comment by ilyaskuzu** [comment]
hi, when installed manually i get;

ImportError: cannot import name 'Error' from 'yutiriti' (xxxxx/.venv-10/lib/python3.10/site-packages/yutiriti-1.0.0-py3.10.egg/yutiriti/__init__.py)

**Comment by ixoon** [comment]
Can someone teach me how how to use kanashi, do i have to know victim password ?
do i need to change username in main code on kanashi ?

**Comment by hxAri** [comment]
Hey everyone, thank you for visiting here, it seems that currently a lot of the **Instagram API** schemes have changed, and I haven't had time to update **Kanashi** again at this time, and if you encounter errors even though you have installed **Yutiriti**, it may be due to the lack of operating system support because **Kanashi** & **Yutiriti** only runs on **Unix/Linux** platforms, I don't use **Windows** so maybe that's a bit of a problem, as soon as I finish my office work I will patch **Kanashi** so that it doesn't have any dependency dependencies with **Yutiriti**
